### ISSUE TITLE
如何滚动到tableview 顶部

### ISSUE THREAD

**Issue by MaricleZhang** [lyb5834/YBWebViewScrollNestView#1]
如何滚动到tableview 顶部，导航栏底部和tableview的顶部同一位置

**Comment by lyb5834** [comment]
滚动`webView.scrollView.contentSize.height`的距离即可

**Comment by MaricleZhang** [comment]
谢谢您的回复。我这里的需求是进入页面，只显示下面的评论tableView，这时候webview 还在加载中，contentSize 还未确定。可以实现吗。再次感谢！

**Comment by lyb5834** [comment]
不太好实现，我这框架一直靠监听`scrollView.contentSize` 实现嵌套滚动的，`webview`还在加载中，那`tableViewHeader`的高度也不确定，很难实现一直显示`tableView`

**Comment by MaricleZhang** [comment]
好的，谢谢

**Comment by lyb5834** [comment]
我更新了一版，增加了可以滚动到tableView的位置的api，不过还是要在网页加载完成后调用

**Comment by MaricleZhang** [comment]
大佬 666

**Comment by MaricleZhang** [comment]
在 webview 的 - (void)webView:(WKWebView *)webView didFinishNavigation:(WKNavigation *)navigation 代理方法中设置scrollToTableViewAnimated，我的问题解决了，太棒了！！！
