### ISSUE TITLE
只能tableview嘛？collectionView可以嘛？

### ISSUE THREAD

**Issue by xiaoyao20084321** [lyb5834/YBWebViewScrollNestView#3]
大佬，只能tableview嘛？collectionView可以嘛？

**Comment by lyb5834** [comment]
因为这个框架本质上是为了解决我自己项目的问题而开发的，根本没考虑collectionview 等其它情况，你看看能不能把tableview 替换成collectionview能不能解决- -

**Comment by xiaoyao20084321** [comment]
好的，感谢大佬，主要是我们现在有个需求。就是下面的是评论嘛，每个评论又有二级评论（回复），然后二级评论整体有一个背景色和圆角。然后我打算实现方式是主评论用section的header，回复评论用row。  然后tableView给section的row设置圆角和背景色不好设置。所以我打算用collectionView来做。
类似与下面这种
![image](https://github.com/user-attachments/assets/bd47a9a0-6a0e-4414-9ec1-2207f07079d2)

**Comment by lyb5834** [comment]
> 好的，感谢大佬，主要是我们现在有个需求。就是下面的是评论嘛，每个评论又有二级评论（回复），然后二级评论整体有一个背景色和圆角。然后我打算实现方式是主评论用section的header，回复评论用row。 然后tableView给section的row设置圆角和背景色不好设置。所以我打算用collectionView来做。 类似与下面这种 ![image](https://private-user-images.githubusercontent.com/10344550/367237554-bd47a9a0-6a0e-4414-9ec1-2207f07079d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjA2MjIsIm5iZiI6MTcyNjIyMDMyMiwicGF0aCI6Ii8xMDM0NDU1MC8zNjcyMzc1NTQtYmQ0N2E5YTAtNmEwZS00NDE0LTllYzEtMjIwN2YwNzA3OWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA5Mzg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NTkzYTNjMDEyMmIyZjBmYjMxNzgzOTg4MjdjNjEzZTU2ZDVjZDliY2E0ZjllMDc2OGMyNTNmNzA0MzdjOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z3kgcEqes6vNCxjl0R6TQDUsiUoFKxSwaSYiRhuo4so)

这种tableview做没什么问题的，多级展开的tableview github上就有现成的

**Comment by xiaoyao20084321** [comment]
大佬有推荐的多级展开的没。。。我在github上找了好久。。没找到合适的啊。。。

**Comment by lyb5834** [comment]
[RATreeView](https://github.com/Augustyniak/RATreeView)  @xiaoyao20084321  你看看行不行

**Comment by xiaoyao20084321** [comment]
好滴，多谢。我看看
